version: "3.8"

services:
    cryptoway-api:
        build: ./cryptoway-api
        image: cryptoway-api
        ports:
            - 3000:3000
        restart: always
        logging:
            driver: "json-file"

    cryptoway-bot:
        build: ./cryptoway-bot
        image: cryptoway-bot
        ports:
            - 5000:5000
        depends_on:
            - cryptoway-api
            - db
        restart: always
        logging:
            driver: "json-file"

    db:
        image: postgres:15.2
        ports:
            - "5433:5432"
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: eN3hv9nDnaq318fb
            POSTGRES_DB: cryptoway
        volumes:
            - ./pgdata:/var/lib/postgresql/data